---
  language: go
  sudo: true
  notifications:
    email: true
  go:
    - stable
    - tip
  services:
    - docker
  env:
    global:
      - GO15VENDOREXPERIMENT=1
  matrix:
    allow_failures:
      - go: tip
    fast_finish: true
  install:
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/staticcheck
  script:
    - go build -v
    - go vet $(go list ./... | grep -v vendor)
    - staticcheck $(go list ./... | grep -v vendor)
    - test -z "$(golint ./... | grep -v vendor | tee /dev/stderr)"
    - test -z "$(gofmt -s -l . | grep -v vendor | tee /dev/stderr)"
    - DOCKER_API_VERSION=1.35 make dind dtest
    - make release
  after_success:
    - bash <(curl -s https://codecov.io/bash)
  deploy:
    provider: releases
    api_key:
      secure: dfGfZqYt5MGEifIKWtb0jlQsJbrOR5TGEIXZOILBW/X6KNB0RqDEghEsU1Z9ob4/a3AuwBJtwUxS9QfqCiy2wApWgG1vlm9li0CFknlgNu8Rsh8iX/D4nOx1oE58jmsibsFcrIu07OQ8YYxBdT9F0r9Cx0WAuGRnPPozfEVu0mO8LMYf9qEM/WnLxDpXSgVXGtPGnkqIONCjdEOZNlsRt31x2XUCryfCs80Ym7ZKvhobnls5JaN0UeoY6YEw54//LeFo6Vqjdlnw8nBttjk2unSc3c2Ty+UrZp6rXCjdlarWlcs1QFV/nriidl0o2qnqC6hayiQTAkOpAqg/l4KxvVBM0KyoZ9xb33/61kOQii9YSgbYj0imTbz6RXcZsTWLp7zVQ/7GNuye3jEPIIBp3M1oqOKP7pS+BM2fydHbKAGt2Eo4v+cbLFPL6M/Xx7nwfFp22Laz2QFM12hKYKR1+XOewMWkJlWVygpFL8vZ5i0PwOVa28QmdKCUjaTpZQdDh9suo910DXEKs3Rhb8OwssSSO7c7kWoE+0DgaCZS/t/BbsZmj8OunMwl5n/kJhA9pfrg+fAQS/szOR8w1BITjcECqATJ+Oo+zy8CWM26l8fyv/3ooEvK+W7g5wTq9bn4L7yV1VgdNSIsj0ODrHMtxYog/NAl38uYPe6MngBWuhs=
    file:
      - cross/reg-linux-amd64.md5
      - cross/reg-windows-386.sha256
      - cross/reg-linux-arm
      - cross/reg-darwin-amd64.md5
      - cross/reg-darwin-amd64
      - cross/reg-linux-arm64.sha256
      - cross/reg-linux-arm.sha256
      - cross/reg-linux-386.sha256
      - cross/reg-darwin-386.md5
      - cross/reg-windows-386.md5
      - cross/reg-linux-arm64.md5
      - cross/reg-linux-arm64
      - cross/reg-linux-amd64.sha256
      - cross/reg-linux-386.md5
      - cross/reg-windows-amd64
      - cross/reg-windows-amd64.md5
      - cross/reg-windows-amd64.sha256
      - cross/reg-linux-arm.md5
      - cross/reg-darwin-386.sha256
      - cross/reg-darwin-amd64.sha256
      - cross/reg-windows-386
      - cross/reg-darwin-386
      - cross/reg-linux-386
      - cross/reg-linux-amd64
    skip_cleanup: true
    on:
      go: stable
      tags: true
